name: Portfolio CI pipeline

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_URL: alloue-yapi-anselme

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Dependencies installation
        run: npm ci

      - name: Project Building
        run: npx ng build --base-href "/${{ env.BASE_URL }}/" --output-path "dist/${{ env.BASE_URL }}"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/${{ env.BASE_URL }}/browser
          publish_branch: gh-pages